### PR TITLE
add country filters to country drop down

### LINKED ISSUE #118: Possibility to filter the CountryDropdown widget items
It's a common use case that sometimes we need to filter the countries 
For example, I need to limit the user to select from 3 countries. Not the whole countries 

We can have a `FilterItems` parameter or an `items` parameter for this widget.

Also, should mention that I can work on this issue

### PR DESCRIPTION
**Pull request by payam-zahedi**
Hi @caseyryan 

I just found a free time in my week and Fixed #118 issue.

Please take a look at it, and if it needs any changes, please let me know.

### CODE REVIEW

**Comment by caseyryan** [comment]
Hi! Thanks for your work. But could you please make it compatible with the latest version of the package? I also made changes to CountryDropdown a few days ago

**Comment by payam-zahedi** [comment]
Hey man 
I just create my fork about 3 hours ago

Should I pull main branch again?

**Comment by caseyryan** [comment]
> Hey man I just create my fork about 3 hours ago
> 
> Should I pull main branch again?

Yes. I edited the above comment . Your branch has no conflicts but it will bring back initialCountryCode parameter, which I decided to remove

**Comment by payam-zahedi** [comment]
So this change is not in your master branch

Did you add it in any branch? Or I should bring back the initialPhoneCode by my self?

**Comment by caseyryan** [comment]
Hi. I had to change your code. It's not a good idea to use getters for initial value. Initial value and the list of values must not be build dynamically. 
This code 
```
PhoneCountryData get _initialValue {
    final items = _countryItems;

    if (widget.initialPhoneCode != null) {
      return items.firstWhereOrNull((c) => c.phoneCode == widget.initialPhoneCode) ??
          items.first;
    }
    return items.first;
  }```
Broke the initial value functionality as the list was always recreated. 
I also renamed the parameter to "filter"

**Comment by payam-zahedi** [comment]
Thanks for your changes

**Comment by payam-zahedi** [comment]
Just to let you know 

If you want to keep some variable like `_initialValue` in your state class, you should also check the didUpdateWidget for incoming changes from the parent.

**Comment by caseyryan** [comment]
Not in this case. Initial value must be idempotent despite the widget state. It's name "initial" by itself means that its value is only set from outside once.

**Comment by payam-zahedi** [comment]
You right.
For initial value we don't needed but what about the `filter`?

**Comment by caseyryan** [comment]
I just renamed the field to make it more specific. I think countryItems may mislead someone because people might think they need to always pass this parameter to make it work at all. In case of filter it makes it clearer that the parameter is only used when you need to filter out some particular countries

**Pull request merged**
