### PR TITLE
fix: use proper format for congo phone numbers

### PR DESCRIPTION
**Pull request by jeffscaturro-aka**
## Description

What an awesome package you've put together! I started using this in a project, and came across an incorrect formatting for phone numbers in the Republic of Congo.

## Motivation and Context

In order to provide the correct format for a phone input for the Republic of Congo, I had to update the mask in `lib/formatters/phone_input_formatter.dart`. The proper mask should be `+000 00 00 00000`. [Reference](https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Republic_of_the_Congo#:~:text=To%20call%20in%20the%20Republic,outside%20Republic%20of%20the%20Congo)

## Changes Made

Updated the mask to use the proper format.

## How to Test

You can use the international code `+242` to start formatting a Congo number.

## Checklist

- [X] I have followed the project's coding style guidelines.
- [X] I have performed a self-review of my code.
- [X] I have written unit tests or provided a rationale for why tests are not necessary.
- [X] I have updated the project documentation if necessary.
- [X] I have added necessary comments and documentation within the code.
- [X] I have tested my changes locally and they work as expected.

## Additional Notes

You currently have two failing tests around the formatting of numbers in the Philippines. I didn't want to touch those in this PR though due to separation of concerns, but wanted to mention it.

### CODE REVIEW

**Comment by jeffscaturro-aka** [comment]
Let me know if you need anything else changed, like the version or something. 

Thank you again, @caseyryan!

**Comment by jeffscaturro-aka** [comment]
Also, for what it's worth, I understand we can use `replacePhoneMask` but it'd also be nice to get this corrected so we don't have to replace it and DRY up some code. :)

**Comment by caseyryan** [comment]
Hi! Impressive work :) Just changing the mask would be enough but you've made a test for it and and the great description. Thank you! I'll merge it as soon as possible
>>> Also, for what it's worth, I understand we can use replacePhoneMask but it'd also be nice to get this corrected so we don't have to replace it and DRY up some code. :)

Exactly. I also thought about it many times but never found time for it so far

**Comment by caseyryan** [comment]
Your fix is now in 2.11.1

**Comment by jeffscaturro-aka** [comment]
Thank you so much for the quick turn around @caseyryan, I appreciate it, and happy to have helped. What you've done with this plugin all together is extremely appreciated. Be well!

**Pull request merged**
