### PR TITLE
fix selection on delete for phone & masked formatters

### PR DESCRIPTION
**Pull request by Andreigr0**
When I ran example on Android I saw that there is improper behaviour on delete using `PhoneInputFormatter` so I made some changes to fix it. (Also fixed typo from `PhoneInputFormater` to `PhoneInputFormatter`)
Also I added some helper getters to `PhoneInputFormatter`: `masked`, `unmasked`, `isFilled`, `mask()` and `masked`, `isFilled` to `MaskedInputFormatter`. These methods allow use formatters without `TextField`
And added `lint` for better code style, though for now I didn't make all changes suggested by it.

### CODE REVIEW

**Comment by caseyryan** [comment]
Hi! What version of phone formatter had a bug? I'm asking because I made some changes to it in the last couple of versions
Unfortunately I don't have time to review the PR right now. I'll try to do it on this weekend

**Comment by Andreigr0** [comment]
I've used last version of package – 1.3.6, there was a bug when I filled text field and tried to remove characters in example app

**Comment by sgehrman** [comment]
@Andreigr0 what flutter channel where you on?  It use to work fine on the stable channel, but broken in the other channels.

There was a bug fix https://github.com/flutter/flutter/pull/75541

But now Flutter 2.0.1 Stable isn't working.  I'm just wondering if this fix is working around a bug in Flutter?

**Review by caseyryan — APPROVED** [review]
Looks like it's ok. I'll merge it here but I won't be able to upload the changes to pub.dev until next weekend

**Comment by Andreigr0** [comment]
> @Andreigr0 what flutter channel where you on? It use to work fine on the stable channel, but broken in the other channels.
> 
> There was a bug fix [flutter/flutter#75541](https://github.com/flutter/flutter/pull/75541)
> 
> But now Flutter 2.0.1 Stable isn't working. I'm just wondering if this fix is working around a bug in Flutter?

When I wrote this fix I was on beta channel, don't know what exact version it was, but I suppose it was 1.25.x
Now I switched back to stable channel and nothing changed, everything works

https://user-images.githubusercontent.com/44437712/110288512-2d635180-7ff9-11eb-8b85-434c4760de86.mov

`flutter --version`
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (4 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Pull request merged**
