### PR TITLE
fix number will be changed automatically as 89 or 83

### PR DESCRIPTION
**Pull request by john-chowbus**

### CODE REVIEW

**Comment by caseyryan** [comment]
1) The parameter you've added must be "true" by default. Your current solution will break existing functionality where it is used.
2) Why is this necessary?

**Comment by john-chowbus** [comment]
1.  changed default to true
2. since when I input 89 or 83, the number will changed to 73 automatically.  this is not expected behavior,   do not want it change automatically.    it is not used in rus or aus.

**Comment by caseyryan** [comment]
> 1. changed default to true
> 2. for example, some one do not want to input +1 prefix of phone number in us,   then input 89 or 83, the number will changed to 73 automatically.  this is not expected behavior,   they do not want it change automatically.    and it is not used in rus or aus.

That's a good point. I implemented this behavior when there was no possibility to enter phone numbers without country code. Now it really makes sense

**Comment by caseyryan** [comment]
Your fix is now available in 2.11.2

**Pull request merged**
